cmake_minimum_required(VERSION 3.22)
if(NOT DEFINED TEST_BINARY_ROOT OR NOT DEFINED VERIFIER)
    message(FATAL_ERROR "TEST_BINARY_ROOT and VERIFIER are required")
endif()
# Each case uses a tiny independent source closure and the production verifier.
# No repository source or pinned inventory is mutated.
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef run_id)
set(root "${TEST_BINARY_ROOT}/${run_id}")
file(MAKE_DIRECTORY "${root}")
file(WRITE "${root}/verify.cmake" [=[
include("${VERIFIER}")
_vrhino_tokenizer_absl_placeholder("${CASE_ROOT}" placeholder)
_vrhino_verify_source_inventory("${CASE_ROOT}/tokenizers-cpp"
    "${CASE_ROOT}/inventory.sha256" "${INVENTORY_HASH}" ${placeholder})
]=])
foreach(case valid missing corrupt extra bad_inventory wrong_link newline_link missing_link directory_link)
    set(case_root "${root}/${case}")
    set(link "${case_root}/tokenizers-cpp/sentencepiece/third_party/absl")
    file(MAKE_DIRECTORY "${case_root}/tokenizers-cpp/sentencepiece/third_party"
        "${case_root}/abseil-cpp/absl")
    file(WRITE "${case_root}/tokenizers-cpp/LICENSE" "verified source bytes\n")
    file(SHA256 "${case_root}/tokenizers-cpp/LICENSE" source_hash)
    file(WRITE "${case_root}/inventory.sha256" "${source_hash}  ./LICENSE\n")
    file(SHA256 "${case_root}/inventory.sha256" inventory_hash)
    if(case STREQUAL "directory_link")
        file(MAKE_DIRECTORY "${link}")
    elseif(NOT case STREQUAL "missing_link")
        set(target "../../../abseil-cpp/absl")
        if(case STREQUAL "wrong_link")
            set(target "../../../unverified/absl")
        elseif(case STREQUAL "newline_link")
            string(APPEND target "\n")
        endif()
        if(WIN32)
            file(WRITE "${link}" "${target}")
        else()
            file(CREATE_LINK "${target}" "${link}" SYMBOLIC)
        endif()
    endif()
    if(case STREQUAL "missing")
        file(REMOVE "${case_root}/tokenizers-cpp/LICENSE")
    elseif(case STREQUAL "corrupt")
        file(APPEND "${case_root}/tokenizers-cpp/LICENSE" "corruption")
    elseif(case STREQUAL "extra")
        file(WRITE "${case_root}/tokenizers-cpp/unexpected.h" "extra")
    elseif(case STREQUAL "bad_inventory")
        file(APPEND "${case_root}/inventory.sha256" "corruption")
    endif()
    execute_process(COMMAND "${CMAKE_COMMAND}" "-DVERIFIER=${VERIFIER}"
        "-DCASE_ROOT=${case_root}" "-DINVENTORY_HASH=${inventory_hash}"
        -P "${root}/verify.cmake"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors)
    if(case STREQUAL "valid")
        if(NOT result STREQUAL "0")
            message(FATAL_ERROR "Valid source closure rejected: ${output}${errors}")
        endif()
    elseif(result STREQUAL "0")
        message(FATAL_ERROR "Invalid source closure accepted: ${case}")
    endif()
    message(STATUS "tokenizer source ${case}: PASS")
endforeach()
