# Public default profile: synthetic data, repository-local metadata, Native execution.
# Other compiled harnesses are optional developer qualification tools and require
# explicitly supplied model/oracle inputs. They are never invoked by CTest.
include(CTest)
if(BUILD_TESTING)
    function(vrhino_public_test target label)
        if(TARGET ${target})
            add_test(NAME ${target} COMMAND ${target} ${ARGN})
            set_tests_properties(${target} PROPERTIES LABELS "public;${label}"
                WORKING_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}"
                TIMEOUT 300 RUN_SERIAL TRUE)
        endif()
    endfunction()
    vrhino_public_test(vrhino-host-allocation-tests host)
    vrhino_public_test(vrhino-file-mapping-tests host)
    vrhino_public_test(vrhino-stable-file-verification-tests host)
    vrhino_public_test(vrhino-windows-cache-publication-tests host)
    vrhino_public_test(vrhino-windows-process-tests host)
    if(TARGET vrhino-windows-product-cli-tests)
        vrhino_public_test(vrhino-windows-product-cli-tests host
            "${CMAKE_CURRENT_BINARY_DIR}/vrhino-windows-test"
            $<TARGET_FILE:vrhino-cli-helper-fixture>
            $<TARGET_FILE:vrhino-process-missing-dependency>
            "${CMAKE_CURRENT_BINARY_DIR}/cli-smoke-work")
    endif()
    if(TARGET vrhino-windows-component-archive-tests)
        find_package(Python3 REQUIRED COMPONENTS Interpreter)
        add_test(NAME vrhino-windows-component-archive-tests
            COMMAND "${Python3_EXECUTABLE}" "${CMAKE_CURRENT_SOURCE_DIR}/tests/windows_component_archive_fixture.py"
                $<TARGET_FILE:vrhino-windows-component-archive-tests>)
        set_tests_properties(vrhino-windows-component-archive-tests PROPERTIES
            LABELS "public;host" TIMEOUT 240 RUN_SERIAL TRUE)
    endif()
    vrhino_public_test(vrhino-component-executor-identity-tests host)
    vrhino_public_test(vrhino-neural-graph-tests host)
    vrhino_public_test(vrhino-neural-graph-extension-tests host)
    vrhino_public_test(vrhino-neural-graph-bf16-tests host)
    vrhino_public_test(vrhino-neural-graph-layernorm-tests host)
    vrhino_public_test(vrhino-wan-graph-dual-path-tests host)
    vrhino_public_test(vrhino-wan-graph-optin-tests host)
    vrhino_public_test(vrhino-memory-runtime-tests host)
    vrhino_public_test(vrhino-precision-policy-tests host)
    vrhino_public_test(vrhino-generic-attention-mask-binding-tests host)
    vrhino_public_test(vrhino-run-session-tests host)
    vrhino_public_test(vrhino-json-request-tests host)
    vrhino_public_test(vrhino-run-request-tests host)
    vrhino_public_test(vrhino-job-manager-tests host)
    vrhino_public_test(vrhino-sha256-tests host)
    vrhino_public_test(vrhino-native-progress-tests host)
    vrhino_public_test(vrhino-native-converter-tests host)
    vrhino_public_test(vrhino-preconditioned-int8-tests host)
    vrhino_public_test(vrhino-vrm-verification-tests host)
    vrhino_public_test(vrhino-lip-sync-workflow-tests host)
    vrhino_public_test(vrhino-lip-sync-diffusion-workflow-tests host)
    vrhino_public_test(vrhino-image-filter-tests host)
    vrhino_public_test(vrhino-model-package-tests host)
    vrhino_public_test(vrhino-model-info-tests host)
    vrhino_public_test(vrhino-product-input-schema-tests host)
    vrhino_public_test(vrhino-product-schema-spec-tests host)
    vrhino_public_test(vrhino-release-version-tests host)
    vrhino_public_test(vrhino-native-api-tests host)
    vrhino_public_test(vrhino-native-api-job-tests host)
    vrhino_public_test(vrhino-native-api-event-tests host)
    vrhino_public_test(vrhino-cpp-httplib-legal-tests host)
    vrhino_public_test(vrhino-tokenizer-build-source-tests host)
    vrhino_public_test(vrhino-native-source-acquisition-tests host)
    vrhino_public_test(vrhino-native-pull-orchestration-tests host)
    vrhino_public_test(vrhino-product-schema-successor-orchestration-tests host)
    vrhino_public_test(vrhino-public-musetalk-product-tests host)
    vrhino_public_test(vrhino-public-latentsync-product-tests host)
    vrhino_public_test(vrhino-product-run-preflight-tests host)
    vrhino_public_test(vrhino-product-doctor-tests host)
    vrhino_public_test(vrhino-wan-graph-synthetic-cuda-tests cuda)
    vrhino_public_test(vrhino-neural-graph-cuda-tests cuda)
    vrhino_public_test(vrhino-neural-graph-extension-cuda-tests cuda)
    vrhino_public_test(vrhino-neural-graph-bf16-cuda-tests cuda)
    vrhino_public_test(vrhino-neural-graph-layernorm-cuda-tests cuda)
    vrhino_public_test(vrhino-neural-graph-ltx-cuda-tests cuda)
    vrhino_public_test(vrhino-native-tests cuda)
    vrhino_public_test(vrhino-native-negative-tests cuda)
    vrhino_public_test(vrhino-phase9-quant-tests cuda)
    vrhino_public_test(vrhino-phase10-cuda-memory-tests cuda)
    vrhino_public_test(vrhino-phase20p-last-use-tests cuda)
    vrhino_public_test(vrhino-phase20q-component-tiling-tests cuda)
    vrhino_public_test(vrhino-phase22d-recursive-tiling-tests cuda)
    vrhino_public_test(vrhino-phase20w-component-execution-binding-tests cuda)
    vrhino_public_test(vrhino-conditioning-mask-contract-tests cuda)
    vrhino_public_test(vrhino-precision-operation-contract-tests cuda)
    vrhino_public_test(vrhino-phase19c-cudnn-sdpa cuda)
    vrhino_public_test(vrhino-phase20d-prefix-mask-sdpa cuda)
    vrhino_public_test(vrhino-phase21h-attention-mask-cache cuda)
    vrhino_public_test(vrhino-phase21j-prepared-tensor-tests cuda)
    vrhino_public_test(vrhino-wan-product-integration-tests host "${CMAKE_CURRENT_SOURCE_DIR}/specs")
    vrhino_public_test(vrhino-mochi-product-integration-tests host "${CMAKE_CURRENT_SOURCE_DIR}/specs")
    if(VRHINO_ENABLE_TOKENIZERS)
        add_test(NAME tokenizer-source-fail-closed
            COMMAND bash "${CMAKE_CURRENT_SOURCE_DIR}/tests/tokenizer_source_fail_closed_tests.sh"
                "${VRHINO_TOKENIZER_BUILD_SOURCES}"
                "${CMAKE_CURRENT_SOURCE_DIR}/cmake/RunTokenizerSourceVerification.cmake")
        set_tests_properties(tokenizer-source-fail-closed PROPERTIES
            LABELS "public;host" TIMEOUT 120 RUN_SERIAL TRUE)
    endif()
endif()
